# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)




# USERS
# Delete all existing records
User.delete_all

# Create seed records
User.create(
    :firstname => "Bubba",
    :surname => "Watson",
    :email => "bubba@golf.com",
    :password => "bubba",
    :role => "admin",
    :avatar_file_name => "bubba.jpg",
    :avatar_content_type => "image/jpeg",
    :avatar_file_size => 10806,
    :avatar_updated_at => DateTime.now
)
User.create(
    :firstname => "Tiger",
    :surname => "Woods",
    :email => "tiger@golf.com",
    :password => "tiger",
    :avatar_file_name => "tiger.jpg",
    :avatar_content_type => "image/jpeg",
    :avatar_file_size => 9424,
    :avatar_updated_at => DateTime.now
)
User.create(
    :firstname => "Rory",
    :surname => "McIlroy",
    :email => "rory@golf.com",
    :password => "rory1",
    :avatar_file_name => "rory.jpg",
    :avatar_content_type => "image/jpeg",
    :avatar_file_size => 10993,
    :avatar_updated_at => DateTime.now
)
User.create(
    :firstname => "Darren",
    :surname => "Clarke",
    :email => "darren@golf.com",
    :password => "darren",
    :avatar_file_name => "darren.jpg",
    :avatar_content_type => "image/jpeg",
    :avatar_file_size => 10178,
    :avatar_updated_at => DateTime.now
)
User.create(
    :firstname => "Luke",
    :surname => "Donald",
    :email => "luke@golf.com",
    :password => "luke1",
    :avatar_file_name => "luke.jpg",
    :avatar_content_type => "image/jpeg",
    :avatar_file_size => 9780,
    :avatar_updated_at => DateTime.now
)
User.create(
    :firstname => "Padraig",
    :surname => "Harrington",
    :email => "padraig@golf.com",
    :password => "padraig",
    :avatar_file_name => "padraig.jpg",
    :avatar_content_type => "image/jpeg",
    :avatar_file_size => 13191,
    :avatar_updated_at => DateTime.now
)
User.create(
    :firstname => "Adam",
    :surname => "Scott",
    :email => "adam@golf.com",
    :password => "adam1",
    :avatar_file_name => "adam.jpg",
    :avatar_content_type => "image/jpeg",
    :avatar_file_size => 10593,
    :avatar_updated_at => DateTime.now
)


# HANDICAPS
# =========
Handicap.delete_all

Handicap.create(:user_id => 1,:competition_id => 0,:handicap => 28.0,:date_adjusted => '2011-01-20')
Handicap.create(:user_id => 1,:competition_id => 0,:handicap => 26.7,:date_adjusted => '2012-02-20')
Handicap.create(:user_id => 1,:competition_id => 0,:handicap => 26.8,:date_adjusted => '2012-03-20')
Handicap.create(:user_id => 1,:competition_id => 0,:handicap => 25.1,:date_adjusted => '2012-04-20')
Handicap.create(:user_id => 1,:competition_id => 0,:handicap => 25.1,:date_adjusted => '2012-05-20')
Handicap.create(:user_id => 1,:competition_id => 0,:handicap => 25.2,:date_adjusted => '2012-06-20')
Handicap.create(:user_id => 1,:competition_id => 0,:handicap => 25.3,:date_adjusted => '2012-07-20')
Handicap.create(:user_id => 1,:competition_id => 0,:handicap => 25.3,:date_adjusted => '2012-08-20')
Handicap.create(:user_id => 1,:competition_id => 0,:handicap => 25.0,:date_adjusted => '2012-09-20')
Handicap.create(:user_id => 1,:competition_id => 0,:handicap => 24.0,:date_adjusted => '2012-10-20')
Handicap.create(:user_id => 1,:competition_id => 0,:handicap => 23.0,:date_adjusted => '2012-11-20')
Handicap.create(:user_id => 1,:competition_id => 0,:handicap => 23.1,:date_adjusted => '2012-12-20')
Handicap.create(:user_id => 2,:competition_id => 0,:handicap => 23.1,:date_adjusted => '2011-01-20')
Handicap.create(:user_id => 3,:competition_id => 0,:handicap => 26.2,:date_adjusted => '2011-01-20')
Handicap.create(:user_id => 4,:competition_id => 0,:handicap => 24.8,:date_adjusted => '2011-01-20')
Handicap.create(:user_id => 5,:competition_id => 0,:handicap => 27.5,:date_adjusted => '2011-01-20')
Handicap.create(:user_id => 6,:competition_id => 0,:handicap => 25.5,:date_adjusted => '2011-01-20')
Handicap.create(:user_id => 7,:competition_id => 0,:handicap => 18.0,:date_adjusted => '2011-01-20')
# COURSES
# Delete all existing records
Course.delete_all

# Create new records
Course.create(:name => "Elmgreen",:crest => "courses/elmgreen.jpg",:photo => "courses/elmgreen.jpg",:latitude => 53.387398,:longitude => -6.355505,:address => "Dunsink Lane, Castleknock, Dublin 15")
Course.create(:name => "Headfort Old",:crest => "courses/headfort.jpg",:latitude => 53.723872,:longitude => -6.861017,:address => "Dublin Road, Kells, Co. Meath")
Course.create(:name => "Headfort New",:crest => "courses/headfort.jpg",:latitude => 53.723872,:longitude => -6.861017,:address => "Dublin Road, Kells, Co. Meath")
Course.create(:name => "St. Margarets",:crest => "courses/st_margarets.jpg",:latitude => 53.449216,:longitude => -6.307334,:address => "St. Margarets, Co. Dublin")
Course.create(:name => "Citywest",:crest => "courses/citywest.jpg",:latitude => 53.283222,:longitude => -6.44108,:address => "Saggart, Co. Dublin")
Course.create(:name => "New Forest",:crest => "courses/new_forest.jpg",:latitude => 53.381634,:longitude => -7.420683,:address => "Tyrellspass, Co. Westmeath")
Course.create(:name => "Knightsbrook",:crest => "courses/knightsbrook.jpg",:latitude => 53.549035,:longitude => -6.765509,:address => "Dublin Road, Trim, Co. Meath")
Course.create(:name => "Royal Tara (Blue/Red)",:crest => "courses/royaltara.jpg",:latitude => 53.591607,:longitude => -6.635137,:address => "Bellinter, Navan, Co. Meath")
Course.create(:name => "Royal Tara (Blue/Yellow)",:crest => "courses/royaltara.jpg",:latitude => 53.591607,:longitude => -6.635137,:address => "Bellinter, Navan, Co. Meath")
Course.create(:name => "Royal Tara (Red/Yellow)",:crest => "courses/royaltara.jpg",:latitude => 53.591607,:longitude => -6.635137,:address => "Bellinter, Navan, Co. Meath")
Course.create(:name => "Parknasilla",:crest => "courses/parknasilla.jpg",:latitude => 51.819519,:longitude => -9.865579,:address => "Sneem, Co. Kerry")
Course.create(:name => "Luttrellstown",:crest => "courses/luttrellstown.jpg",:latitude => 53.374648,:longitude => -6.412937,:address => "Castleknock, Dublin 15")
Course.create(:name => "Port Laoise",:crest => "courses/portlaoise.jpg",:latitude => 53.023615,:longitude => -7.298426,:address => "Cork Road, Port Laoise, Co. Laois")
Course.create(:name => "Farnham Estate",:crest => "courses/farnham_estate.jpg",:latitude => 53.997175,:longitude => -7.384236,:address => "Cavan, Co. Cavan")
Course.create(:name => "Tara (special)",:crest => "courses/royaltara.jpg",:latitude => 53.591607,:longitude => -6.635137,:address => "Bellinter, Navan, Co. Meath")
Course.create(:name => "Craddockstown",:crest => "courses/craddockstown.jpg",:latitude => 53.208911,:longitude => -6.639655,:address => "Blessington Road, Naas, Co. Kildare")
Course.create(:name => "Carton House - O'Meara",:crest => "courses/carton.jpg",:latitude => 53.378132,:longitude => -6.554811,:address => "Carton Demesne, Maynooth, Co. Kildare")
Course.create(:name => "Carton House - Montgomerie",:crest => "courses/carton.jpg",:latitude => 53.378132,:longitude => -6.554811,:address => "Carton Demesne, Maynooth, Co. Kildare")
Course.create(:name => "Rathcore",:crest => "courses/rathcore.jpg",:latitude => 53.449574,:longitude => -6.843284,:address => "Rathcore, Enfield, Co. Meath")
Course.create(:name => "Beaverstown",:crest => "courses/beaverstown.jpg",:latitude => 53.497163,:longitude => -6.144518,:address => "Beaverstown, Donabate, Co. Dublin")
Course.create(:name => "Hollystown (Red/Yellow)",:crest => "courses/hollystown.jpg",:latitude => 53.430909,:longitude => -6.376111,:address => "Tyrellstown, Dublin 15")


# ROUNDS
# Delete all existing records
Round.delete_all

# Seed the new records
Round.create(:user_id =>1,:course_id => 7,:tee => 'white',:date_played => '2011-07-20')
Round.create(:user_id =>2,:course_id => 1,:tee => 'blue',:date_played => '2011-07-23')
Round.create(:user_id =>6,:course_id => 8,:tee => 'white',:date_played => '2011-10-27')
Round.create(:user_id =>3,:course_id => 5,:tee => 'white',:date_played => '2011-06-14')
Round.create(:user_id =>5,:course_id => 10,:tee => 'white',:date_played => '2011-10-05')
Round.create(:user_id =>6,:course_id => 11,:tee => 'blue',:date_played => '2011-08-18')
Round.create(:user_id =>2,:course_id => 12,:tee => 'white',:date_played => '2011-11-01')
Round.create(:user_id =>1,:course_id => 3,:tee => 'yellow',:date_played => '2011-11-05')
Round.create(:user_id =>1,:course_id => 7,:tee => 'green',:date_played => '2011-11-11')
Round.create(:user_id =>4,:course_id => 7,:tee => 'green',:date_played => '2011-11-23')
Round.create(:user_id =>4,:course_id => 13,:tee => 'white',:date_played => '2011-10-08')
Round.create(:user_id =>7,:course_id => 7,:tee => 'green',:date_played => '2011-12-22')
Round.create(:user_id =>3,:course_id => 12,:tee => 'white',:date_played => '2012-01-24')
Round.create(:user_id =>5,:course_id => 3,:tee => 'yellow',:date_played => '2012-02-08')
Round.create(:user_id =>6,:course_id => 12,:tee => 'green',:date_played => '2012-02-16')
Round.create(:user_id =>2,:course_id => 14,:tee => 'yellow',:date_played => '2012-02-25')
Round.create(:user_id =>3,:course_id => 15,:tee => 'green',:date_played => '2012-03-01')
Round.create(:user_id =>4,:course_id => 12,:tee => 'green',:date_played => '2012-03-06')
Round.create(:user_id =>7,:course_id => 12,:tee => 'green',:date_played => '2012-03-14')
Round.create(:user_id =>6,:course_id => 17,:tee => 'white',:date_played => '2012-03-28')
Round.create(:user_id =>5,:course_id => 8,:tee => 'white',:date_played => '2012-04-04')
Round.create(:user_id =>4,:course_id => 8,:tee => 'white',:date_played => '2012-04-12')
Round.create(:user_id =>3,:course_id => 18,:tee => 'green',:date_played => '2012-04-18')
Round.create(:user_id =>2,:course_id => 10,:tee => 'white',:date_played => '2012-04-27')
Round.create(:user_id =>1,:course_id => 7,:tee => 'green',:date_played => '2012-05-02')
Round.create(:user_id =>7,:course_id => 2,:tee => 'yellow',:date_played => '2012-05-30')
Round.create(:user_id =>1,:course_id => 7,:tee => 'green',:date_played => '2012-06-06')
Round.create(:user_id =>2,:course_id => 7,:tee => 'green',:date_played => '2012-06-27')
Round.create(:user_id =>3,:course_id => 12,:tee => 'green',:date_played => '2012-06-20')
Round.create(:user_id =>4,:course_id => 19,:tee => 'yellow',:date_played => '2012-07-05')
Round.create(:user_id =>5,:course_id => 20,:tee => 'yellow',:date_played => '2012-07-14')
Round.create(:user_id =>6,:course_id => 12,:tee => 'green',:date_played => '2012-07-30')
Round.create(:user_id =>7,:course_id => 8,:tee => 'white',:date_played => '2012-08-15')
Round.create(:user_id =>6,:course_id => 12,:tee => 'white',:date_played => '2012-08-21')
Round.create(:user_id =>5,:course_id => 19,:tee => 'yellow',:date_played => '2012-08-31')
Round.create(:user_id =>4,:course_id => 7,:tee => 'green',:date_played => '2012-09-04')
Round.create(:user_id =>3,:course_id => 7,:tee => 'green',:date_played => '2012-09-14')
Round.create(:user_id =>2,:course_id => 7,:tee => 'green',:date_played => '2012-10-03')
Round.create(:user_id =>1,:course_id => 8,:tee => 'white',:date_played => '2012-09-28')
Round.create(:user_id =>2,:course_id => 12,:tee => 'green',:date_played => '2012-10-09')
Round.create(:user_id =>4,:course_id => 21,:tee => 'yellow',:date_played => '2012-09-18')
Round.create(:user_id =>6,:course_id => 12,:tee => 'green',:date_played => '2012-10-16')
Round.create(:user_id =>1,:course_id => 18,:tee => 'green',:date_played => '2012-10-22')
Round.create(:user_id =>3,:course_id => 12,:tee => 'green',:date_played => '2012-10-30')
Round.create(:user_id =>5,:course_id => 19,:tee => 'yellow',:date_played => '2012-11-14')
Round.create(:user_id =>7,:course_id => 7,:tee => 'green',:date_played => '2012-11-28')

# Competition rounds
Round.create(:user_id =>1,:course_id => 7,:tee => 'green',:date_played => '2013-01-01', :competition_id => 1)
Round.create(:user_id =>2,:course_id => 7,:tee => 'green',:date_played => '2013-01-01', :competition_id => 1)
Round.create(:user_id =>3,:course_id => 7,:tee => 'green',:date_played => '2013-01-01', :competition_id => 1)
Round.create(:user_id =>4,:course_id => 7,:tee => 'green',:date_played => '2013-01-01', :competition_id => 1)
Round.create(:user_id =>5,:course_id => 7,:tee => 'green',:date_played => '2013-01-01', :competition_id => 1)
Round.create(:user_id =>6,:course_id => 7,:tee => 'green',:date_played => '2013-01-01', :competition_id => 1)
Round.create(:user_id =>7,:course_id => 7,:tee => 'green',:date_played => '2013-01-01', :competition_id => 1)


#COMPETITIONS
Competition.delete_all

Competition.create(:course_id => 7, :competition_date => '2013-01-01', :css => 72)




# POSTS
# Delete all existing records
Post.delete_all

Post.create(
    :user_id => 1,
    :title => "Welcome to TeeMates!",
    :message => "This is the place where our golf society will promote and organise its activities.  This wall allows
                  society members to interact with each other through posts and comments.  You will be able to upload
                  photos, videos and messages, which your colleagues can comment on. Keep it civil!"
)

Post.create(
    :user_id => 4,
    :title => "Carton House",
    :message => "Taken this morning on the Montgomerie Course. Fantastic morning for it...",
    :photo_file_name => "carton.jpg",
    :photo_content_type => "image/jpeg",
    :photo_file_size =>2506910,
    :photo_updated_at => DateTime.now
)




# COMMENTS
# ========

Comment.delete_all

Comment.create(:post_id => 1, :comment => "Excellent - I love it!", :user_id => 2)
Comment.create(:post_id => 1, :comment => "Yeah, it should be great.  Looking forward to the competitions!", :user_id => 3)
Comment.create(:post_id => 1, :comment => "Super job - I'm impressed", :user_id => 4)
Comment.create(:post_id => 1, :comment => "Any 'like' button?", :user_id => 2)
Comment.create(:post_id => 1, :comment => "This isn't Facebook!", :user_id => 5)
Comment.create(:post_id => 1, :comment => "We'll look at implementing a 'like' function sometime in a later release.", :user_id => 1)
Comment.create(:post_id => 1, :comment => "That'll do!", :user_id => 2)
Comment.create(:post_id => 2, :comment => "That is just stunning!", :user_id => 2)
Comment.create(:post_id => 2, :comment => "^ What he said!", :user_id => 7)
Comment.create(:post_id => 2, :comment => "We're you out today and didn't call me?", :user_id => 6)
Comment.create(:post_id => 2, :comment => "Eh, yeah...", :user_id => 4)



# SCORECARDS
# Delete all existing records
Scorecard.delete_all

# Create new records
Scorecard.create(:round_id => 1, :hole_id => 1, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 1, :hole_id => 2, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 1, :hole_id => 3, :strokes => 5, :putts => 3)
Scorecard.create(:round_id => 1, :hole_id => 4, :strokes => 8, :putts => 3)
Scorecard.create(:round_id => 1, :hole_id => 5, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 1, :hole_id => 6, :strokes => 7, :putts => 3)
Scorecard.create(:round_id => 1, :hole_id => 7, :strokes => 6, :putts => 1)
Scorecard.create(:round_id => 1, :hole_id => 8, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 1, :hole_id => 9, :strokes => 9, :putts => 3)
Scorecard.create(:round_id => 1, :hole_id => 10, :strokes => 4, :putts => 1)
Scorecard.create(:round_id => 1, :hole_id => 11, :strokes => 9, :putts => 3)
Scorecard.create(:round_id => 1, :hole_id => 12, :strokes => 9, :putts => 3)
Scorecard.create(:round_id => 1, :hole_id => 13, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 1, :hole_id => 14, :strokes => 5, :putts => 3)
Scorecard.create(:round_id => 1, :hole_id => 15, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 1, :hole_id => 16, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 1, :hole_id => 17, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 1, :hole_id => 18, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 2, :hole_id => 19, :strokes => 5, :putts => nil)
Scorecard.create(:round_id => 2, :hole_id => 20, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 2, :hole_id => 21, :strokes => 8, :putts => nil)
Scorecard.create(:round_id => 2, :hole_id => 22, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 2, :hole_id => 23, :strokes => 5, :putts => nil)
Scorecard.create(:round_id => 2, :hole_id => 24, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 2, :hole_id => 25, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 2, :hole_id => 26, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 2, :hole_id => 27, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 2, :hole_id => 28, :strokes => 5, :putts => nil)
Scorecard.create(:round_id => 2, :hole_id => 29, :strokes => 4, :putts => nil)
Scorecard.create(:round_id => 2, :hole_id => 30, :strokes => 5, :putts => nil)
Scorecard.create(:round_id => 2, :hole_id => 31, :strokes => 4, :putts => nil)
Scorecard.create(:round_id => 2, :hole_id => 32, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 2, :hole_id => 33, :strokes => 8, :putts => nil)
Scorecard.create(:round_id => 2, :hole_id => 34, :strokes => 8, :putts => nil)
Scorecard.create(:round_id => 2, :hole_id => 35, :strokes => 5, :putts => nil)
Scorecard.create(:round_id => 2, :hole_id => 36, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 3, :hole_id => 73, :strokes => 8, :putts => 2)
Scorecard.create(:round_id => 3, :hole_id => 74, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 3, :hole_id => 75, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 3, :hole_id => 76, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 3, :hole_id => 77, :strokes => 2, :putts => 1)
Scorecard.create(:round_id => 3, :hole_id => 78, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 3, :hole_id => 79, :strokes => 7, :putts => 3)
Scorecard.create(:round_id => 3, :hole_id => 80, :strokes => 5, :putts => 3)
Scorecard.create(:round_id => 3, :hole_id => 81, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 3, :hole_id => 109, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 3, :hole_id => 110, :strokes => 4, :putts => 3)
Scorecard.create(:round_id => 3, :hole_id => 111, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 3, :hole_id => 112, :strokes => 3, :putts => 2)
Scorecard.create(:round_id => 3, :hole_id => 113, :strokes => 8, :putts => 4)
Scorecard.create(:round_id => 3, :hole_id => 114, :strokes => 3, :putts => 2)
Scorecard.create(:round_id => 3, :hole_id => 115, :strokes => 7, :putts => 3)
Scorecard.create(:round_id => 3, :hole_id => 116, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 3, :hole_id => 117, :strokes => 9, :putts => 2)
Scorecard.create(:round_id => 4, :hole_id => 91, :strokes => 8, :putts => nil)
Scorecard.create(:round_id => 4, :hole_id => 92, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 4, :hole_id => 93, :strokes => 3, :putts => nil)
Scorecard.create(:round_id => 4, :hole_id => 94, :strokes => 4, :putts => nil)
Scorecard.create(:round_id => 4, :hole_id => 95, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 4, :hole_id => 96, :strokes => 5, :putts => nil)
Scorecard.create(:round_id => 4, :hole_id => 97, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 4, :hole_id => 98, :strokes => 7, :putts => nil)
Scorecard.create(:round_id => 4, :hole_id => 99, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 4, :hole_id => 100, :strokes => 4, :putts => nil)
Scorecard.create(:round_id => 4, :hole_id => 101, :strokes => 7, :putts => nil)
Scorecard.create(:round_id => 4, :hole_id => 102, :strokes => 5, :putts => nil)
Scorecard.create(:round_id => 4, :hole_id => 103, :strokes => 9, :putts => nil)
Scorecard.create(:round_id => 4, :hole_id => 104, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 4, :hole_id => 105, :strokes => 7, :putts => nil)
Scorecard.create(:round_id => 4, :hole_id => 106, :strokes => 9, :putts => nil)
Scorecard.create(:round_id => 4, :hole_id => 107, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 4, :hole_id => 108, :strokes => 11, :putts => nil)
Scorecard.create(:round_id => 5, :hole_id => 82, :strokes => 8, :putts => nil)
Scorecard.create(:round_id => 5, :hole_id => 83, :strokes => 7, :putts => nil)
Scorecard.create(:round_id => 5, :hole_id => 84, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 5, :hole_id => 85, :strokes => 5, :putts => nil)
Scorecard.create(:round_id => 5, :hole_id => 86, :strokes => 8, :putts => nil)
Scorecard.create(:round_id => 5, :hole_id => 87, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 5, :hole_id => 88, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 5, :hole_id => 89, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 5, :hole_id => 90, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 5, :hole_id => 118, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 5, :hole_id => 119, :strokes => 4, :putts => nil)
Scorecard.create(:round_id => 5, :hole_id => 120, :strokes => 9, :putts => nil)
Scorecard.create(:round_id => 5, :hole_id => 121, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 5, :hole_id => 122, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 5, :hole_id => 123, :strokes => 5, :putts => nil)
Scorecard.create(:round_id => 5, :hole_id => 124, :strokes => 5, :putts => nil)
Scorecard.create(:round_id => 5, :hole_id => 125, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 5, :hole_id => 126, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 6, :hole_id => 127, :strokes => 5, :putts => nil)
Scorecard.create(:round_id => 6, :hole_id => 128, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 6, :hole_id => 129, :strokes => 5, :putts => nil)
Scorecard.create(:round_id => 6, :hole_id => 130, :strokes => 3, :putts => nil)
Scorecard.create(:round_id => 6, :hole_id => 131, :strokes => 5, :putts => nil)
Scorecard.create(:round_id => 6, :hole_id => 132, :strokes => 4, :putts => nil)
Scorecard.create(:round_id => 6, :hole_id => 133, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 6, :hole_id => 134, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 6, :hole_id => 135, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 6, :hole_id => 136, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 6, :hole_id => 137, :strokes => 8, :putts => nil)
Scorecard.create(:round_id => 6, :hole_id => 138, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 7, :hole_id => 139, :strokes => 8, :putts => 3)
Scorecard.create(:round_id => 7, :hole_id => 140, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 7, :hole_id => 141, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 7, :hole_id => 142, :strokes => 5, :putts => 3)
Scorecard.create(:round_id => 7, :hole_id => 143, :strokes => 10, :putts => 3)
Scorecard.create(:round_id => 7, :hole_id => 144, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 7, :hole_id => 145, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 7, :hole_id => 146, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 7, :hole_id => 147, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 7, :hole_id => 148, :strokes => 7, :putts => 3)
Scorecard.create(:round_id => 7, :hole_id => 149, :strokes => 4, :putts => 1)
Scorecard.create(:round_id => 7, :hole_id => 150, :strokes => 7, :putts => 3)
Scorecard.create(:round_id => 7, :hole_id => 151, :strokes => 7, :putts => 3)
Scorecard.create(:round_id => 7, :hole_id => 152, :strokes => 8, :putts => 2)
Scorecard.create(:round_id => 7, :hole_id => 153, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 7, :hole_id => 154, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 7, :hole_id => 155, :strokes => 8, :putts => 2)
Scorecard.create(:round_id => 7, :hole_id => 156, :strokes => 8, :putts => 2)
Scorecard.create(:round_id => 8, :hole_id => 157, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 8, :hole_id => 176, :strokes => 9, :putts => 2)
Scorecard.create(:round_id => 8, :hole_id => 177, :strokes => 8, :putts => 3)
Scorecard.create(:round_id => 8, :hole_id => 178, :strokes => 3, :putts => 1)
Scorecard.create(:round_id => 8, :hole_id => 179, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 8, :hole_id => 180, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 8, :hole_id => 181, :strokes => 8, :putts => 4)
Scorecard.create(:round_id => 8, :hole_id => 182, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 8, :hole_id => 183, :strokes => 7, :putts => 3)
Scorecard.create(:round_id => 8, :hole_id => 184, :strokes => 5, :putts => 3)
Scorecard.create(:round_id => 8, :hole_id => 185, :strokes => 4, :putts => 3)
Scorecard.create(:round_id => 8, :hole_id => 186, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 8, :hole_id => 187, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 8, :hole_id => 188, :strokes => 8, :putts => 3)
Scorecard.create(:round_id => 8, :hole_id => 189, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 8, :hole_id => 190, :strokes => 9, :putts => 2)
Scorecard.create(:round_id => 8, :hole_id => 191, :strokes => 3, :putts => 1)
Scorecard.create(:round_id => 8, :hole_id => 192, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 9, :hole_id => 193, :strokes => 9, :putts => 3)
Scorecard.create(:round_id => 9, :hole_id => 194, :strokes => 9, :putts => 2)
Scorecard.create(:round_id => 9, :hole_id => 195, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 9, :hole_id => 196, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 9, :hole_id => 197, :strokes => 4, :putts => 3)
Scorecard.create(:round_id => 9, :hole_id => 198, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 9, :hole_id => 199, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 9, :hole_id => 200, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 9, :hole_id => 201, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 9, :hole_id => 202, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 9, :hole_id => 203, :strokes => 10, :putts => 1)
Scorecard.create(:round_id => 9, :hole_id => 204, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 9, :hole_id => 205, :strokes => 8, :putts => 2)
Scorecard.create(:round_id => 9, :hole_id => 206, :strokes => 8, :putts => 2)
Scorecard.create(:round_id => 10, :hole_id => 193, :strokes => 7, :putts => 4)
Scorecard.create(:round_id => 10, :hole_id => 194, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 10, :hole_id => 195, :strokes => 4, :putts => 3)
Scorecard.create(:round_id => 10, :hole_id => 196, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 10, :hole_id => 197, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 10, :hole_id => 198, :strokes => 8, :putts => 2)
Scorecard.create(:round_id => 10, :hole_id => 199, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 10, :hole_id => 200, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 10, :hole_id => 201, :strokes => 7, :putts => 3)
Scorecard.create(:round_id => 10, :hole_id => 202, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 10, :hole_id => 203, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 10, :hole_id => 204, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 10, :hole_id => 205, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 10, :hole_id => 206, :strokes => 5, :putts => 1)
Scorecard.create(:round_id => 10, :hole_id => 207, :strokes => 4, :putts => 1)
Scorecard.create(:round_id => 10, :hole_id => 208, :strokes => 3, :putts => 2)
Scorecard.create(:round_id => 10, :hole_id => 209, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 10, :hole_id => 210, :strokes => 4, :putts => 3)
Scorecard.create(:round_id => 11, :hole_id => 211, :strokes => 5, :putts => nil)
Scorecard.create(:round_id => 11, :hole_id => 212, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 11, :hole_id => 213, :strokes => 7, :putts => nil)
Scorecard.create(:round_id => 11, :hole_id => 214, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 11, :hole_id => 215, :strokes => 5, :putts => nil)
Scorecard.create(:round_id => 11, :hole_id => 216, :strokes => 8, :putts => nil)
Scorecard.create(:round_id => 11, :hole_id => 217, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 11, :hole_id => 218, :strokes => 7, :putts => nil)
Scorecard.create(:round_id => 11, :hole_id => 219, :strokes => 3, :putts => nil)
Scorecard.create(:round_id => 11, :hole_id => 220, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 11, :hole_id => 221, :strokes => 7, :putts => nil)
Scorecard.create(:round_id => 11, :hole_id => 222, :strokes => 4, :putts => nil)
Scorecard.create(:round_id => 11, :hole_id => 223, :strokes => 7, :putts => nil)
Scorecard.create(:round_id => 11, :hole_id => 224, :strokes => 5, :putts => nil)
Scorecard.create(:round_id => 11, :hole_id => 225, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 11, :hole_id => 226, :strokes => 3, :putts => nil)
Scorecard.create(:round_id => 11, :hole_id => 227, :strokes => 5, :putts => nil)
Scorecard.create(:round_id => 11, :hole_id => 228, :strokes => 4, :putts => nil)
Scorecard.create(:round_id => 12, :hole_id => 193, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 12, :hole_id => 194, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 12, :hole_id => 195, :strokes => 4, :putts => 3)
Scorecard.create(:round_id => 12, :hole_id => 196, :strokes => 9, :putts => 2)
Scorecard.create(:round_id => 12, :hole_id => 197, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 12, :hole_id => 198, :strokes => 6, :putts => 1)
Scorecard.create(:round_id => 12, :hole_id => 199, :strokes => 9, :putts => 3)
Scorecard.create(:round_id => 12, :hole_id => 200, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 12, :hole_id => 201, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 12, :hole_id => 202, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 12, :hole_id => 203, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 12, :hole_id => 204, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 12, :hole_id => 205, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 12, :hole_id => 206, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 12, :hole_id => 207, :strokes => 7, :putts => 3)
Scorecard.create(:round_id => 12, :hole_id => 208, :strokes => 3, :putts => 2)
Scorecard.create(:round_id => 12, :hole_id => 209, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 12, :hole_id => 210, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 13, :hole_id => 139, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 13, :hole_id => 140, :strokes => 8, :putts => 3)
Scorecard.create(:round_id => 13, :hole_id => 141, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 13, :hole_id => 142, :strokes => 8, :putts => 4)
Scorecard.create(:round_id => 13, :hole_id => 143, :strokes => 7, :putts => 3)
Scorecard.create(:round_id => 13, :hole_id => 144, :strokes => 4, :putts => 3)
Scorecard.create(:round_id => 13, :hole_id => 145, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 13, :hole_id => 146, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 13, :hole_id => 147, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 13, :hole_id => 148, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 13, :hole_id => 149, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 13, :hole_id => 150, :strokes => 9, :putts => 2)
Scorecard.create(:round_id => 13, :hole_id => 151, :strokes => 3, :putts => 2)
Scorecard.create(:round_id => 14, :hole_id => 157, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 14, :hole_id => 176, :strokes => 9, :putts => 3)
Scorecard.create(:round_id => 14, :hole_id => 177, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 14, :hole_id => 178, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 14, :hole_id => 179, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 14, :hole_id => 180, :strokes => 9, :putts => 2)
Scorecard.create(:round_id => 14, :hole_id => 181, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 14, :hole_id => 182, :strokes => 6, :putts => 1)
Scorecard.create(:round_id => 14, :hole_id => 183, :strokes => 9, :putts => 2)
Scorecard.create(:round_id => 14, :hole_id => 184, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 14, :hole_id => 185, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 14, :hole_id => 186, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 14, :hole_id => 187, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 14, :hole_id => 188, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 14, :hole_id => 189, :strokes => 8, :putts => 2)
Scorecard.create(:round_id => 14, :hole_id => 190, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 14, :hole_id => 191, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 14, :hole_id => 192, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 15, :hole_id => 229, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 15, :hole_id => 230, :strokes => 5, :putts => nil)
Scorecard.create(:round_id => 15, :hole_id => 231, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 15, :hole_id => 232, :strokes => 5, :putts => nil)
Scorecard.create(:round_id => 15, :hole_id => 233, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 15, :hole_id => 234, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 15, :hole_id => 235, :strokes => 5, :putts => nil)
Scorecard.create(:round_id => 15, :hole_id => 236, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 15, :hole_id => 237, :strokes => 7, :putts => nil)
Scorecard.create(:round_id => 15, :hole_id => 238, :strokes => 7, :putts => nil)
Scorecard.create(:round_id => 15, :hole_id => 239, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 15, :hole_id => 240, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 15, :hole_id => 241, :strokes => 4, :putts => nil)
Scorecard.create(:round_id => 15, :hole_id => 242, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 15, :hole_id => 243, :strokes => 3, :putts => nil)
Scorecard.create(:round_id => 15, :hole_id => 244, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 15, :hole_id => 245, :strokes => 8, :putts => nil)
Scorecard.create(:round_id => 15, :hole_id => 246, :strokes => 9, :putts => nil)
Scorecard.create(:round_id => 16, :hole_id => 247, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 16, :hole_id => 248, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 16, :hole_id => 249, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 16, :hole_id => 250, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 16, :hole_id => 251, :strokes => 4, :putts => 3)
Scorecard.create(:round_id => 16, :hole_id => 252, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 16, :hole_id => 253, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 16, :hole_id => 254, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 16, :hole_id => 255, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 16, :hole_id => 256, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 16, :hole_id => 257, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 16, :hole_id => 258, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 16, :hole_id => 259, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 16, :hole_id => 260, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 16, :hole_id => 261, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 16, :hole_id => 262, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 16, :hole_id => 263, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 16, :hole_id => 264, :strokes => 7, :putts => 3)
Scorecard.create(:round_id => 17, :hole_id => 265, :strokes => 7, :putts => 1)
Scorecard.create(:round_id => 17, :hole_id => 266, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 17, :hole_id => 267, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 17, :hole_id => 268, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 17, :hole_id => 269, :strokes => 2, :putts => 1)
Scorecard.create(:round_id => 17, :hole_id => 270, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 17, :hole_id => 271, :strokes => 5, :putts => 1)
Scorecard.create(:round_id => 17, :hole_id => 272, :strokes => 3, :putts => 1)
Scorecard.create(:round_id => 17, :hole_id => 273, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 17, :hole_id => 274, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 17, :hole_id => 275, :strokes => 3, :putts => 1)
Scorecard.create(:round_id => 17, :hole_id => 276, :strokes => 7, :putts => 1)
Scorecard.create(:round_id => 17, :hole_id => 277, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 17, :hole_id => 278, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 17, :hole_id => 279, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 17, :hole_id => 280, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 17, :hole_id => 281, :strokes => 8, :putts => 3)
Scorecard.create(:round_id => 17, :hole_id => 282, :strokes => 10, :putts => 3)
Scorecard.create(:round_id => 18, :hole_id => 229, :strokes => 7, :putts => 3)
Scorecard.create(:round_id => 18, :hole_id => 230, :strokes => 7, :putts => 3)
Scorecard.create(:round_id => 18, :hole_id => 231, :strokes => 7, :putts => 3)
Scorecard.create(:round_id => 18, :hole_id => 232, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 18, :hole_id => 233, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 18, :hole_id => 234, :strokes => 3, :putts => 1)
Scorecard.create(:round_id => 18, :hole_id => 235, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 18, :hole_id => 236, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 18, :hole_id => 237, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 18, :hole_id => 238, :strokes => 7, :putts => 3)
Scorecard.create(:round_id => 18, :hole_id => 239, :strokes => 4, :putts => 1)
Scorecard.create(:round_id => 18, :hole_id => 240, :strokes => 8, :putts => 3)
Scorecard.create(:round_id => 18, :hole_id => 241, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 18, :hole_id => 242, :strokes => 6, :putts => 1)
Scorecard.create(:round_id => 18, :hole_id => 243, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 18, :hole_id => 244, :strokes => 5, :putts => 1)
Scorecard.create(:round_id => 18, :hole_id => 245, :strokes => 4, :putts => 1)
Scorecard.create(:round_id => 18, :hole_id => 246, :strokes => 8, :putts => 2)
Scorecard.create(:round_id => 19, :hole_id => 229, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 19, :hole_id => 230, :strokes => 5, :putts => 1)
Scorecard.create(:round_id => 19, :hole_id => 231, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 19, :hole_id => 232, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 19, :hole_id => 233, :strokes => 7, :putts => 3)
Scorecard.create(:round_id => 19, :hole_id => 234, :strokes => 6, :putts => 1)
Scorecard.create(:round_id => 19, :hole_id => 235, :strokes => 8, :putts => 2)
Scorecard.create(:round_id => 19, :hole_id => 236, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 19, :hole_id => 237, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 19, :hole_id => 238, :strokes => 8, :putts => 3)
Scorecard.create(:round_id => 19, :hole_id => 239, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 19, :hole_id => 240, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 19, :hole_id => 241, :strokes => 3, :putts => 2)
Scorecard.create(:round_id => 19, :hole_id => 242, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 19, :hole_id => 243, :strokes => 5, :putts => 3)
Scorecard.create(:round_id => 19, :hole_id => 244, :strokes => 7, :putts => 3)
Scorecard.create(:round_id => 19, :hole_id => 245, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 19, :hole_id => 246, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 20, :hole_id => 319, :strokes => 7, :putts => nil)
Scorecard.create(:round_id => 20, :hole_id => 320, :strokes => 7, :putts => nil)
Scorecard.create(:round_id => 20, :hole_id => 321, :strokes => 8, :putts => nil)
Scorecard.create(:round_id => 20, :hole_id => 322, :strokes => 5, :putts => nil)
Scorecard.create(:round_id => 20, :hole_id => 323, :strokes => 7, :putts => nil)
Scorecard.create(:round_id => 20, :hole_id => 324, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 20, :hole_id => 325, :strokes => 4, :putts => nil)
Scorecard.create(:round_id => 20, :hole_id => 326, :strokes => 7, :putts => nil)
Scorecard.create(:round_id => 20, :hole_id => 327, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 20, :hole_id => 328, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 20, :hole_id => 329, :strokes => 7, :putts => nil)
Scorecard.create(:round_id => 20, :hole_id => 330, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 20, :hole_id => 331, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 20, :hole_id => 332, :strokes => 7, :putts => nil)
Scorecard.create(:round_id => 20, :hole_id => 333, :strokes => 7, :putts => nil)
Scorecard.create(:round_id => 20, :hole_id => 334, :strokes => 3, :putts => nil)
Scorecard.create(:round_id => 20, :hole_id => 335, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 20, :hole_id => 336, :strokes => 7, :putts => nil)
Scorecard.create(:round_id => 21, :hole_id => 73, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 21, :hole_id => 74, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 21, :hole_id => 75, :strokes => 8, :putts => nil)
Scorecard.create(:round_id => 21, :hole_id => 76, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 21, :hole_id => 77, :strokes => 4, :putts => nil)
Scorecard.create(:round_id => 21, :hole_id => 78, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 21, :hole_id => 79, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 21, :hole_id => 80, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 21, :hole_id => 81, :strokes => 8, :putts => nil)
Scorecard.create(:round_id => 21, :hole_id => 109, :strokes => 5, :putts => nil)
Scorecard.create(:round_id => 21, :hole_id => 110, :strokes => 5, :putts => nil)
Scorecard.create(:round_id => 21, :hole_id => 111, :strokes => 4, :putts => nil)
Scorecard.create(:round_id => 21, :hole_id => 112, :strokes => 3, :putts => nil)
Scorecard.create(:round_id => 21, :hole_id => 113, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 21, :hole_id => 114, :strokes => 5, :putts => nil)
Scorecard.create(:round_id => 21, :hole_id => 115, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 21, :hole_id => 116, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 21, :hole_id => 117, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 22, :hole_id => 73, :strokes => 8, :putts => 4)
Scorecard.create(:round_id => 22, :hole_id => 74, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 22, :hole_id => 75, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 22, :hole_id => 76, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 22, :hole_id => 77, :strokes => 3, :putts => 2)
Scorecard.create(:round_id => 22, :hole_id => 78, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 22, :hole_id => 79, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 22, :hole_id => 80, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 22, :hole_id => 81, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 22, :hole_id => 109, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 22, :hole_id => 110, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 22, :hole_id => 111, :strokes => 9, :putts => 2)
Scorecard.create(:round_id => 22, :hole_id => 112, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 22, :hole_id => 113, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 22, :hole_id => 114, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 22, :hole_id => 115, :strokes => 5, :putts => 1)
Scorecard.create(:round_id => 22, :hole_id => 116, :strokes => 7, :putts => 4)
Scorecard.create(:round_id => 22, :hole_id => 117, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 23, :hole_id => 337, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 23, :hole_id => 338, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 23, :hole_id => 339, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 23, :hole_id => 340, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 23, :hole_id => 341, :strokes => 10, :putts => 4)
Scorecard.create(:round_id => 23, :hole_id => 342, :strokes => 7, :putts => 3)
Scorecard.create(:round_id => 23, :hole_id => 343, :strokes => 5, :putts => 3)
Scorecard.create(:round_id => 23, :hole_id => 344, :strokes => 8, :putts => 3)
Scorecard.create(:round_id => 23, :hole_id => 345, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 23, :hole_id => 346, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 23, :hole_id => 347, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 23, :hole_id => 348, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 23, :hole_id => 349, :strokes => 5, :putts => 3)
Scorecard.create(:round_id => 23, :hole_id => 350, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 23, :hole_id => 351, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 23, :hole_id => 352, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 23, :hole_id => 353, :strokes => 5, :putts => 4)
Scorecard.create(:round_id => 23, :hole_id => 354, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 24, :hole_id => 82, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 24, :hole_id => 83, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 24, :hole_id => 84, :strokes => 8, :putts => 3)
Scorecard.create(:round_id => 24, :hole_id => 85, :strokes => 4, :putts => 0)
Scorecard.create(:round_id => 24, :hole_id => 86, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 24, :hole_id => 87, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 24, :hole_id => 88, :strokes => 5, :putts => 1)
Scorecard.create(:round_id => 24, :hole_id => 89, :strokes => 9, :putts => 2)
Scorecard.create(:round_id => 24, :hole_id => 90, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 24, :hole_id => 118, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 24, :hole_id => 119, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 24, :hole_id => 120, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 24, :hole_id => 121, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 24, :hole_id => 122, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 24, :hole_id => 123, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 24, :hole_id => 124, :strokes => 4, :putts => 1)
Scorecard.create(:round_id => 24, :hole_id => 125, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 24, :hole_id => 126, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 25, :hole_id => 193, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 25, :hole_id => 194, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 25, :hole_id => 195, :strokes => 3, :putts => 1)
Scorecard.create(:round_id => 25, :hole_id => 196, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 25, :hole_id => 197, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 25, :hole_id => 198, :strokes => 6, :putts => 1)
Scorecard.create(:round_id => 25, :hole_id => 199, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 25, :hole_id => 200, :strokes => 8, :putts => 2)
Scorecard.create(:round_id => 25, :hole_id => 201, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 25, :hole_id => 202, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 25, :hole_id => 203, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 25, :hole_id => 204, :strokes => 8, :putts => 4)
Scorecard.create(:round_id => 25, :hole_id => 205, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 25, :hole_id => 206, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 25, :hole_id => 207, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 25, :hole_id => 208, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 25, :hole_id => 209, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 25, :hole_id => 210, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 26, :hole_id => 55, :strokes => 5, :putts => nil)
Scorecard.create(:round_id => 26, :hole_id => 56, :strokes => 5, :putts => nil)
Scorecard.create(:round_id => 26, :hole_id => 57, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 26, :hole_id => 58, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 26, :hole_id => 59, :strokes => 5, :putts => nil)
Scorecard.create(:round_id => 26, :hole_id => 60, :strokes => 5, :putts => nil)
Scorecard.create(:round_id => 26, :hole_id => 61, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 26, :hole_id => 62, :strokes => 5, :putts => nil)
Scorecard.create(:round_id => 26, :hole_id => 63, :strokes => 4, :putts => nil)
Scorecard.create(:round_id => 26, :hole_id => 64, :strokes => 3, :putts => nil)
Scorecard.create(:round_id => 26, :hole_id => 65, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 26, :hole_id => 66, :strokes => 7, :putts => nil)
Scorecard.create(:round_id => 26, :hole_id => 67, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 26, :hole_id => 68, :strokes => 4, :putts => nil)
Scorecard.create(:round_id => 26, :hole_id => 69, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 26, :hole_id => 70, :strokes => 7, :putts => nil)
Scorecard.create(:round_id => 26, :hole_id => 71, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 26, :hole_id => 72, :strokes => 5, :putts => nil)
Scorecard.create(:round_id => 27, :hole_id => 193, :strokes => 5, :putts => 3)
Scorecard.create(:round_id => 27, :hole_id => 194, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 27, :hole_id => 195, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 27, :hole_id => 196, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 27, :hole_id => 197, :strokes => 5, :putts => 3)
Scorecard.create(:round_id => 27, :hole_id => 198, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 27, :hole_id => 199, :strokes => 6, :putts => 1)
Scorecard.create(:round_id => 27, :hole_id => 200, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 27, :hole_id => 201, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 27, :hole_id => 202, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 27, :hole_id => 203, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 27, :hole_id => 204, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 27, :hole_id => 205, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 27, :hole_id => 206, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 27, :hole_id => 207, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 27, :hole_id => 208, :strokes => 4, :putts => 3)
Scorecard.create(:round_id => 27, :hole_id => 209, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 27, :hole_id => 210, :strokes => 4, :putts => 3)
Scorecard.create(:round_id => 28, :hole_id => 193, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 28, :hole_id => 194, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 28, :hole_id => 195, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 28, :hole_id => 196, :strokes => 5, :putts => 1)
Scorecard.create(:round_id => 28, :hole_id => 197, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 28, :hole_id => 198, :strokes => 9, :putts => 3)
Scorecard.create(:round_id => 28, :hole_id => 199, :strokes => 5, :putts => 1)
Scorecard.create(:round_id => 28, :hole_id => 200, :strokes => 8, :putts => 2)
Scorecard.create(:round_id => 28, :hole_id => 201, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 28, :hole_id => 202, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 28, :hole_id => 203, :strokes => 3, :putts => 1)
Scorecard.create(:round_id => 28, :hole_id => 204, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 28, :hole_id => 205, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 28, :hole_id => 206, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 28, :hole_id => 207, :strokes => 9, :putts => 3)
Scorecard.create(:round_id => 28, :hole_id => 208, :strokes => 5, :putts => 1)
Scorecard.create(:round_id => 28, :hole_id => 209, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 28, :hole_id => 210, :strokes => 3, :putts => 3)
Scorecard.create(:round_id => 29, :hole_id => 229, :strokes => 5, :putts => nil)
Scorecard.create(:round_id => 29, :hole_id => 230, :strokes => 7, :putts => nil)
Scorecard.create(:round_id => 29, :hole_id => 231, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 29, :hole_id => 232, :strokes => 4, :putts => nil)
Scorecard.create(:round_id => 29, :hole_id => 233, :strokes => 7, :putts => nil)
Scorecard.create(:round_id => 29, :hole_id => 234, :strokes => 5, :putts => nil)
Scorecard.create(:round_id => 29, :hole_id => 235, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 29, :hole_id => 236, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 29, :hole_id => 237, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 29, :hole_id => 238, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 29, :hole_id => 239, :strokes => 4, :putts => nil)
Scorecard.create(:round_id => 29, :hole_id => 240, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 29, :hole_id => 241, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 29, :hole_id => 242, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 29, :hole_id => 243, :strokes => 5, :putts => nil)
Scorecard.create(:round_id => 29, :hole_id => 244, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 29, :hole_id => 245, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 29, :hole_id => 246, :strokes => 9, :putts => nil)
Scorecard.create(:round_id => 30, :hole_id => 373, :strokes => 6, :putts => 1)
Scorecard.create(:round_id => 30, :hole_id => 374, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 30, :hole_id => 375, :strokes => 8, :putts => 2)
Scorecard.create(:round_id => 30, :hole_id => 376, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 30, :hole_id => 377, :strokes => 6, :putts => 1)
Scorecard.create(:round_id => 30, :hole_id => 378, :strokes => 7, :putts => 1)
Scorecard.create(:round_id => 30, :hole_id => 379, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 30, :hole_id => 380, :strokes => 9, :putts => 2)
Scorecard.create(:round_id => 30, :hole_id => 381, :strokes => 7, :putts => 3)
Scorecard.create(:round_id => 30, :hole_id => 382, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 30, :hole_id => 383, :strokes => 5, :putts => 3)
Scorecard.create(:round_id => 30, :hole_id => 384, :strokes => 5, :putts => 1)
Scorecard.create(:round_id => 30, :hole_id => 385, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 30, :hole_id => 386, :strokes => 4, :putts => 1)
Scorecard.create(:round_id => 30, :hole_id => 387, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 30, :hole_id => 388, :strokes => 5, :putts => 1)
Scorecard.create(:round_id => 30, :hole_id => 389, :strokes => 4, :putts => 1)
Scorecard.create(:round_id => 30, :hole_id => 390, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 31, :hole_id => 391, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 31, :hole_id => 392, :strokes => 5, :putts => 3)
Scorecard.create(:round_id => 31, :hole_id => 393, :strokes => 6, :putts => 4)
Scorecard.create(:round_id => 31, :hole_id => 394, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 31, :hole_id => 395, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 31, :hole_id => 396, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 31, :hole_id => 397, :strokes => 3, :putts => 2)
Scorecard.create(:round_id => 31, :hole_id => 398, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 31, :hole_id => 399, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 31, :hole_id => 400, :strokes => 5, :putts => 3)
Scorecard.create(:round_id => 31, :hole_id => 401, :strokes => 4, :putts => 1)
Scorecard.create(:round_id => 31, :hole_id => 402, :strokes => 5, :putts => 1)
Scorecard.create(:round_id => 31, :hole_id => 403, :strokes => 8, :putts => 2)
Scorecard.create(:round_id => 31, :hole_id => 404, :strokes => 6, :putts => 1)
Scorecard.create(:round_id => 31, :hole_id => 405, :strokes => 4, :putts => 1)
Scorecard.create(:round_id => 31, :hole_id => 406, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 31, :hole_id => 407, :strokes => 5, :putts => 1)
Scorecard.create(:round_id => 31, :hole_id => 408, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 32, :hole_id => 229, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 32, :hole_id => 230, :strokes => 7, :putts => 1)
Scorecard.create(:round_id => 32, :hole_id => 231, :strokes => 8, :putts => 2)
Scorecard.create(:round_id => 32, :hole_id => 232, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 32, :hole_id => 233, :strokes => 7, :putts => 1)
Scorecard.create(:round_id => 32, :hole_id => 234, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 32, :hole_id => 235, :strokes => 8, :putts => 3)
Scorecard.create(:round_id => 32, :hole_id => 236, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 32, :hole_id => 237, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 32, :hole_id => 238, :strokes => 7, :putts => 1)
Scorecard.create(:round_id => 32, :hole_id => 239, :strokes => 8, :putts => 2)
Scorecard.create(:round_id => 32, :hole_id => 240, :strokes => 8, :putts => 3)
Scorecard.create(:round_id => 32, :hole_id => 241, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 32, :hole_id => 242, :strokes => 4, :putts => 1)
Scorecard.create(:round_id => 32, :hole_id => 243, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 32, :hole_id => 244, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 32, :hole_id => 245, :strokes => 5, :putts => 3)
Scorecard.create(:round_id => 32, :hole_id => 246, :strokes => 12, :putts => 2)
Scorecard.create(:round_id => 33, :hole_id => 73, :strokes => 7, :putts => 1)
Scorecard.create(:round_id => 33, :hole_id => 74, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 33, :hole_id => 75, :strokes => 4, :putts => 1)
Scorecard.create(:round_id => 33, :hole_id => 76, :strokes => 8, :putts => 3)
Scorecard.create(:round_id => 33, :hole_id => 77, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 33, :hole_id => 78, :strokes => 6, :putts => 1)
Scorecard.create(:round_id => 33, :hole_id => 79, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 33, :hole_id => 80, :strokes => 5, :putts => 1)
Scorecard.create(:round_id => 33, :hole_id => 81, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 34, :hole_id => 139, :strokes => 8, :putts => 3)
Scorecard.create(:round_id => 34, :hole_id => 140, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 34, :hole_id => 141, :strokes => 5, :putts => 1)
Scorecard.create(:round_id => 34, :hole_id => 142, :strokes => 5, :putts => 3)
Scorecard.create(:round_id => 34, :hole_id => 143, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 34, :hole_id => 144, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 34, :hole_id => 145, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 34, :hole_id => 146, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 34, :hole_id => 147, :strokes => 5, :putts => 3)
Scorecard.create(:round_id => 34, :hole_id => 148, :strokes => 6, :putts => 1)
Scorecard.create(:round_id => 34, :hole_id => 149, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 34, :hole_id => 150, :strokes => 8, :putts => nil)
Scorecard.create(:round_id => 34, :hole_id => 151, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 34, :hole_id => 152, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 34, :hole_id => 153, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 34, :hole_id => 154, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 34, :hole_id => 155, :strokes => 7, :putts => 3)
Scorecard.create(:round_id => 34, :hole_id => 156, :strokes => 8, :putts => 3)
Scorecard.create(:round_id => 35, :hole_id => 373, :strokes => 7, :putts => 1)
Scorecard.create(:round_id => 35, :hole_id => 374, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 35, :hole_id => 375, :strokes => 8, :putts => 3)
Scorecard.create(:round_id => 35, :hole_id => 376, :strokes => 3, :putts => 2)
Scorecard.create(:round_id => 35, :hole_id => 377, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 35, :hole_id => 378, :strokes => 5, :putts => 1)
Scorecard.create(:round_id => 35, :hole_id => 379, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 35, :hole_id => 380, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 35, :hole_id => 381, :strokes => 3, :putts => 2)
Scorecard.create(:round_id => 35, :hole_id => 382, :strokes => 5, :putts => 1)
Scorecard.create(:round_id => 35, :hole_id => 383, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 35, :hole_id => 384, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 35, :hole_id => 385, :strokes => 7, :putts => 3)
Scorecard.create(:round_id => 35, :hole_id => 386, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 35, :hole_id => 387, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 35, :hole_id => 388, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 35, :hole_id => 389, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 35, :hole_id => 390, :strokes => 7, :putts => 1)
Scorecard.create(:round_id => 36, :hole_id => 193, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 36, :hole_id => 194, :strokes => 6, :putts => 1)
Scorecard.create(:round_id => 36, :hole_id => 195, :strokes => 3, :putts => 2)
Scorecard.create(:round_id => 36, :hole_id => 196, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 36, :hole_id => 197, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 36, :hole_id => 198, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 36, :hole_id => 199, :strokes => 4, :putts => 1)
Scorecard.create(:round_id => 36, :hole_id => 200, :strokes => 7, :putts => 3)
Scorecard.create(:round_id => 36, :hole_id => 201, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 36, :hole_id => 202, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 36, :hole_id => 203, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 36, :hole_id => 204, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 36, :hole_id => 205, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 36, :hole_id => 206, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 36, :hole_id => 207, :strokes => 8, :putts => 2)
Scorecard.create(:round_id => 36, :hole_id => 208, :strokes => 3, :putts => 2)
Scorecard.create(:round_id => 36, :hole_id => 209, :strokes => 6, :putts => 1)
Scorecard.create(:round_id => 36, :hole_id => 210, :strokes => 4, :putts => 3)
Scorecard.create(:round_id => 37, :hole_id => 193, :strokes => 8, :putts => 3)
Scorecard.create(:round_id => 37, :hole_id => 194, :strokes => 7, :putts => 3)
Scorecard.create(:round_id => 37, :hole_id => 195, :strokes => 3, :putts => 2)
Scorecard.create(:round_id => 37, :hole_id => 196, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 37, :hole_id => 197, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 37, :hole_id => 198, :strokes => 6, :putts => 1)
Scorecard.create(:round_id => 37, :hole_id => 199, :strokes => 6, :putts => 1)
Scorecard.create(:round_id => 37, :hole_id => 200, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 37, :hole_id => 201, :strokes => 7, :putts => 3)
Scorecard.create(:round_id => 37, :hole_id => 202, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 37, :hole_id => 203, :strokes => 7, :putts => 4)
Scorecard.create(:round_id => 37, :hole_id => 204, :strokes => 7, :putts => 3)
Scorecard.create(:round_id => 37, :hole_id => 205, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 37, :hole_id => 206, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 37, :hole_id => 207, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 37, :hole_id => 208, :strokes => 3, :putts => 2)
Scorecard.create(:round_id => 37, :hole_id => 209, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 37, :hole_id => 210, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 38, :hole_id => 193, :strokes => 5, :putts => nil)
Scorecard.create(:round_id => 38, :hole_id => 194, :strokes => 7, :putts => nil)
Scorecard.create(:round_id => 38, :hole_id => 195, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 38, :hole_id => 196, :strokes => 7, :putts => nil)
Scorecard.create(:round_id => 38, :hole_id => 197, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 38, :hole_id => 198, :strokes => 7, :putts => nil)
Scorecard.create(:round_id => 38, :hole_id => 199, :strokes => 5, :putts => nil)
Scorecard.create(:round_id => 38, :hole_id => 200, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 38, :hole_id => 201, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 38, :hole_id => 202, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 38, :hole_id => 203, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 38, :hole_id => 204, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 38, :hole_id => 205, :strokes => 6, :putts => nil)
Scorecard.create(:round_id => 38, :hole_id => 206, :strokes => 5, :putts => nil)
Scorecard.create(:round_id => 38, :hole_id => 207, :strokes => 8, :putts => nil)
Scorecard.create(:round_id => 38, :hole_id => 208, :strokes => 3, :putts => nil)
Scorecard.create(:round_id => 38, :hole_id => 209, :strokes => 7, :putts => nil)
Scorecard.create(:round_id => 38, :hole_id => 210, :strokes => 5, :putts => nil)
Scorecard.create(:round_id => 39, :hole_id => 73, :strokes => 10, :putts => 4)
Scorecard.create(:round_id => 39, :hole_id => 74, :strokes => 8, :putts => 3)
Scorecard.create(:round_id => 39, :hole_id => 75, :strokes => 8, :putts => 2)
Scorecard.create(:round_id => 39, :hole_id => 76, :strokes => 8, :putts => 2)
Scorecard.create(:round_id => 39, :hole_id => 77, :strokes => 5, :putts => 1)
Scorecard.create(:round_id => 39, :hole_id => 78, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 39, :hole_id => 79, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 39, :hole_id => 80, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 39, :hole_id => 81, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 39, :hole_id => 109, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 39, :hole_id => 110, :strokes => 5, :putts => 3)
Scorecard.create(:round_id => 39, :hole_id => 111, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 39, :hole_id => 112, :strokes => 3, :putts => 1)
Scorecard.create(:round_id => 39, :hole_id => 113, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 39, :hole_id => 114, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 39, :hole_id => 115, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 39, :hole_id => 116, :strokes => 3, :putts => 1)
Scorecard.create(:round_id => 39, :hole_id => 117, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 40, :hole_id => 229, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 40, :hole_id => 230, :strokes => 8, :putts => 2)
Scorecard.create(:round_id => 40, :hole_id => 231, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 40, :hole_id => 232, :strokes => 5, :putts => 3)
Scorecard.create(:round_id => 40, :hole_id => 233, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 40, :hole_id => 234, :strokes => 5, :putts => 3)
Scorecard.create(:round_id => 40, :hole_id => 235, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 40, :hole_id => 236, :strokes => 6, :putts => 1)
Scorecard.create(:round_id => 40, :hole_id => 237, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 40, :hole_id => 238, :strokes => 4, :putts => 1)
Scorecard.create(:round_id => 40, :hole_id => 239, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 40, :hole_id => 240, :strokes => 7, :putts => 1)
Scorecard.create(:round_id => 40, :hole_id => 241, :strokes => 4, :putts => 3)
Scorecard.create(:round_id => 40, :hole_id => 242, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 40, :hole_id => 243, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 40, :hole_id => 244, :strokes => 5, :putts => 0)
Scorecard.create(:round_id => 40, :hole_id => 245, :strokes => 7, :putts => 3)
Scorecard.create(:round_id => 40, :hole_id => 246, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 41, :hole_id => 409, :strokes => 8, :putts => 2)
Scorecard.create(:round_id => 41, :hole_id => 410, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 41, :hole_id => 411, :strokes => 5, :putts => 3)
Scorecard.create(:round_id => 41, :hole_id => 412, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 41, :hole_id => 413, :strokes => 8, :putts => 2)
Scorecard.create(:round_id => 41, :hole_id => 414, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 41, :hole_id => 415, :strokes => 3, :putts => 2)
Scorecard.create(:round_id => 41, :hole_id => 416, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 41, :hole_id => 417, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 41, :hole_id => 418, :strokes => 5, :putts => 1)
Scorecard.create(:round_id => 41, :hole_id => 419, :strokes => 3, :putts => 4)
Scorecard.create(:round_id => 41, :hole_id => 420, :strokes => 9, :putts => 2)
Scorecard.create(:round_id => 41, :hole_id => 421, :strokes => 4, :putts => 1)
Scorecard.create(:round_id => 41, :hole_id => 422, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 41, :hole_id => 423, :strokes => 3, :putts => 1)
Scorecard.create(:round_id => 41, :hole_id => 424, :strokes => 8, :putts => 2)
Scorecard.create(:round_id => 41, :hole_id => 425, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 41, :hole_id => 426, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 42, :hole_id => 229, :strokes => 7, :putts => 4)
Scorecard.create(:round_id => 42, :hole_id => 230, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 42, :hole_id => 231, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 42, :hole_id => 232, :strokes => 4, :putts => 3)
Scorecard.create(:round_id => 42, :hole_id => 233, :strokes => 7, :putts => 1)
Scorecard.create(:round_id => 42, :hole_id => 234, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 42, :hole_id => 235, :strokes => 6, :putts => 4)
Scorecard.create(:round_id => 42, :hole_id => 236, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 42, :hole_id => 237, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 42, :hole_id => 238, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 42, :hole_id => 239, :strokes => 7, :putts => 4)
Scorecard.create(:round_id => 42, :hole_id => 240, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 42, :hole_id => 241, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 42, :hole_id => 242, :strokes => 7, :putts => 4)
Scorecard.create(:round_id => 42, :hole_id => 243, :strokes => 5, :putts => 3)
Scorecard.create(:round_id => 42, :hole_id => 244, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 42, :hole_id => 245, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 42, :hole_id => 246, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 43, :hole_id => 337, :strokes => 7, :putts => 3)
Scorecard.create(:round_id => 43, :hole_id => 338, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 43, :hole_id => 339, :strokes => 3, :putts => 1)
Scorecard.create(:round_id => 43, :hole_id => 340, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 43, :hole_id => 341, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 43, :hole_id => 342, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 43, :hole_id => 343, :strokes => 3, :putts => 1)
Scorecard.create(:round_id => 43, :hole_id => 344, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 43, :hole_id => 345, :strokes => 4, :putts => 1)
Scorecard.create(:round_id => 43, :hole_id => 346, :strokes => 7, :putts => 3)
Scorecard.create(:round_id => 43, :hole_id => 347, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 43, :hole_id => 348, :strokes => 5, :putts => 3)
Scorecard.create(:round_id => 43, :hole_id => 349, :strokes => 5, :putts => 3)
Scorecard.create(:round_id => 43, :hole_id => 350, :strokes => 5, :putts => 3)
Scorecard.create(:round_id => 43, :hole_id => 351, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 43, :hole_id => 352, :strokes => 5, :putts => 1)
Scorecard.create(:round_id => 43, :hole_id => 353, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 43, :hole_id => 354, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 44, :hole_id => 229, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 44, :hole_id => 230, :strokes => 6, :putts => 1)
Scorecard.create(:round_id => 44, :hole_id => 231, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 44, :hole_id => 232, :strokes => 3, :putts => 1)
Scorecard.create(:round_id => 44, :hole_id => 233, :strokes => 7, :putts => 3)
Scorecard.create(:round_id => 44, :hole_id => 234, :strokes => 3, :putts => 2)
Scorecard.create(:round_id => 44, :hole_id => 235, :strokes => 6, :putts => 1)
Scorecard.create(:round_id => 44, :hole_id => 236, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 44, :hole_id => 237, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 44, :hole_id => 238, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 44, :hole_id => 239, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 44, :hole_id => 240, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 44, :hole_id => 241, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 44, :hole_id => 242, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 44, :hole_id => 243, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 44, :hole_id => 244, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 44, :hole_id => 245, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 44, :hole_id => 246, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 45, :hole_id => 373, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 45, :hole_id => 374, :strokes => 8, :putts => 3)
Scorecard.create(:round_id => 45, :hole_id => 375, :strokes => 5, :putts => 3)
Scorecard.create(:round_id => 45, :hole_id => 376, :strokes => 3, :putts => 2)
Scorecard.create(:round_id => 45, :hole_id => 377, :strokes => 6, :putts => 1)
Scorecard.create(:round_id => 45, :hole_id => 378, :strokes => 6, :putts => 1)
Scorecard.create(:round_id => 45, :hole_id => 379, :strokes => 6, :putts => 1)
Scorecard.create(:round_id => 45, :hole_id => 380, :strokes => 9, :putts => 2)
Scorecard.create(:round_id => 45, :hole_id => 381, :strokes => 3, :putts => 2)
Scorecard.create(:round_id => 45, :hole_id => 382, :strokes => 5, :putts => 1)
Scorecard.create(:round_id => 45, :hole_id => 383, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 45, :hole_id => 384, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 45, :hole_id => 385, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 45, :hole_id => 386, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 45, :hole_id => 387, :strokes => 6, :putts => 1)
Scorecard.create(:round_id => 45, :hole_id => 388, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 45, :hole_id => 389, :strokes => 5, :putts => 1)
Scorecard.create(:round_id => 45, :hole_id => 390, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 46, :hole_id => 193, :strokes => 5, :putts => 1)
Scorecard.create(:round_id => 46, :hole_id => 194, :strokes => 8, :putts => 4)
Scorecard.create(:round_id => 46, :hole_id => 195, :strokes => 3, :putts => 2)
Scorecard.create(:round_id => 46, :hole_id => 196, :strokes => nil, :putts => nil)
Scorecard.create(:round_id => 46, :hole_id => 197, :strokes => 3, :putts => 2)
Scorecard.create(:round_id => 46, :hole_id => 198, :strokes => 5, :putts => 1)
Scorecard.create(:round_id => 46, :hole_id => 199, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 46, :hole_id => 200, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 46, :hole_id => 201, :strokes => 5, :putts => 1)
Scorecard.create(:round_id => 46, :hole_id => 202, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 46, :hole_id => 203, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 46, :hole_id => 204, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 46, :hole_id => 205, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 46, :hole_id => 206, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 46, :hole_id => 207, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 46, :hole_id => 208, :strokes => 6, :putts => 3)
Scorecard.create(:round_id => 46, :hole_id => 209, :strokes => 7, :putts => 1)
Scorecard.create(:round_id => 46, :hole_id => 210, :strokes => 3, :putts => 1)

# Competition rounds
# user_id = 1
Scorecard.create(:round_id => 47, :hole_id => 193, :strokes => 5, :putts => 3)
Scorecard.create(:round_id => 47, :hole_id => 194, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 47, :hole_id => 195, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 47, :hole_id => 196, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 47, :hole_id => 197, :strokes => 5, :putts => 3)
Scorecard.create(:round_id => 47, :hole_id => 198, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 47, :hole_id => 199, :strokes => 6, :putts => 1)
Scorecard.create(:round_id => 47, :hole_id => 200, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 47, :hole_id => 201, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 47, :hole_id => 202, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 47, :hole_id => 203, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 47, :hole_id => 204, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 47, :hole_id => 205, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 47, :hole_id => 206, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 47, :hole_id => 207, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 47, :hole_id => 208, :strokes => 4, :putts => 3)
Scorecard.create(:round_id => 47, :hole_id => 209, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 47, :hole_id => 210, :strokes => 4, :putts => 3)

# user_id = 2
Scorecard.create(:round_id => 48, :hole_id => 193, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 48, :hole_id => 194, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 48, :hole_id => 195, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 48, :hole_id => 196, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 48, :hole_id => 197, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 48, :hole_id => 198, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 48, :hole_id => 199, :strokes => 5, :putts => 1)
Scorecard.create(:round_id => 48, :hole_id => 200, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 48, :hole_id => 201, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 48, :hole_id => 202, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 48, :hole_id => 203, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 48, :hole_id => 204, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 48, :hole_id => 205, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 48, :hole_id => 206, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 48, :hole_id => 207, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 48, :hole_id => 208, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 48, :hole_id => 209, :strokes => 4, :putts => 1)
Scorecard.create(:round_id => 48, :hole_id => 210, :strokes => 3, :putts => 2)

# user_id = 3
Scorecard.create(:round_id => 49, :hole_id => 193, :strokes => 5, :putts => 3)
Scorecard.create(:round_id => 49, :hole_id => 194, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 49, :hole_id => 195, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 49, :hole_id => 196, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 49, :hole_id => 197, :strokes => 5, :putts => 3)
Scorecard.create(:round_id => 49, :hole_id => 198, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 49, :hole_id => 199, :strokes => 6, :putts => 1)
Scorecard.create(:round_id => 49, :hole_id => 200, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 49, :hole_id => 201, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 49, :hole_id => 202, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 49, :hole_id => 203, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 49, :hole_id => 204, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 49, :hole_id => 205, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 49, :hole_id => 206, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 49, :hole_id => 207, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 49, :hole_id => 208, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 49, :hole_id => 209, :strokes => 4, :putts => 1)
Scorecard.create(:round_id => 49, :hole_id => 210, :strokes => 3, :putts => 2)

# user_id = 4
Scorecard.create(:round_id => 50, :hole_id => 193, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 50, :hole_id => 194, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 50, :hole_id => 195, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 50, :hole_id => 196, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 50, :hole_id => 197, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 50, :hole_id => 198, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 50, :hole_id => 199, :strokes => 5, :putts => 1)
Scorecard.create(:round_id => 50, :hole_id => 200, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 50, :hole_id => 201, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 50, :hole_id => 202, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 50, :hole_id => 203, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 50, :hole_id => 204, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 50, :hole_id => 205, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 50, :hole_id => 206, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 50, :hole_id => 207, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 50, :hole_id => 208, :strokes => 4, :putts => 3)
Scorecard.create(:round_id => 50, :hole_id => 209, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 50, :hole_id => 210, :strokes => 4, :putts => 3)

# user_id = 5
Scorecard.create(:round_id => 51, :hole_id => 193, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 51, :hole_id => 194, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 51, :hole_id => 195, :strokes => 3, :putts => 2)
Scorecard.create(:round_id => 51, :hole_id => 196, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 51, :hole_id => 197, :strokes => 3, :putts => 2)
Scorecard.create(:round_id => 51, :hole_id => 198, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 51, :hole_id => 199, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 51, :hole_id => 200, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 51, :hole_id => 201, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 51, :hole_id => 202, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 51, :hole_id => 203, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 51, :hole_id => 204, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 51, :hole_id => 205, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 51, :hole_id => 206, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 51, :hole_id => 207, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 51, :hole_id => 208, :strokes => 3, :putts => 2)
Scorecard.create(:round_id => 51, :hole_id => 209, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 51, :hole_id => 210, :strokes => 3, :putts => 2)

# user_id = 6
Scorecard.create(:round_id => 52, :hole_id => 193, :strokes => 3, :putts => 2)
Scorecard.create(:round_id => 52, :hole_id => 194, :strokes => 3, :putts => 2)
Scorecard.create(:round_id => 52, :hole_id => 195, :strokes => 2, :putts => 2)
Scorecard.create(:round_id => 52, :hole_id => 196, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 52, :hole_id => 197, :strokes => 1, :putts => 0)
Scorecard.create(:round_id => 52, :hole_id => 198, :strokes => 3, :putts => 2)
Scorecard.create(:round_id => 52, :hole_id => 199, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 52, :hole_id => 200, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 52, :hole_id => 201, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 52, :hole_id => 202, :strokes => 3, :putts => 2)
Scorecard.create(:round_id => 52, :hole_id => 203, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 52, :hole_id => 204, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 52, :hole_id => 205, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 52, :hole_id => 206, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 52, :hole_id => 207, :strokes => 3, :putts => 2)
Scorecard.create(:round_id => 52, :hole_id => 208, :strokes => 3, :putts => 2)
Scorecard.create(:round_id => 52, :hole_id => 209, :strokes => 7, :putts => 2)
Scorecard.create(:round_id => 52, :hole_id => 210, :strokes => 3, :putts => 2)

# user_id = 7
Scorecard.create(:round_id => 53, :hole_id => 193, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 53, :hole_id => 194, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 53, :hole_id => 195, :strokes => 3, :putts => 2)
Scorecard.create(:round_id => 53, :hole_id => 196, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 53, :hole_id => 197, :strokes => 3, :putts => 2)
Scorecard.create(:round_id => 53, :hole_id => 198, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 53, :hole_id => 199, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 53, :hole_id => 200, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 53, :hole_id => 201, :strokes => 4, :putts => 2)
Scorecard.create(:round_id => 53, :hole_id => 202, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 53, :hole_id => 203, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 53, :hole_id => 204, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 53, :hole_id => 205, :strokes => 6, :putts => 2)
Scorecard.create(:round_id => 53, :hole_id => 206, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 53, :hole_id => 207, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 53, :hole_id => 208, :strokes => 4, :putts => 3)
Scorecard.create(:round_id => 53, :hole_id => 209, :strokes => 5, :putts => 2)
Scorecard.create(:round_id => 53, :hole_id => 210, :strokes => 4, :putts => 3)
